baseURL: "https://pradep.netlify.app"
languageCode: "en-us"
title: "Pradep Kumar"
theme: hugo-profile
ignoreErrors: ["error-remote-getjson"]

Paginate: 6
disqusShortname: 
googleAnalytics: 

markup:
  goldmark:
    renderer:
      unsafe: true



Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Pradep Kumar"
  description: Pradep's web site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  font:
    # fontSize: 1.5rem # default: 1rem
    # fontWeight: 500 # default: 400
    # lineHeight: 1 # default: 1.5
    textAlign: justify # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Pradep."
    subtitle: "I like to learn new things"
    content: "Full Stack Web Developer who likes gaming with friends. தமிழ் மீது தீரா காதல் கொண்டவன்"
    image: /images/pradep_hero1.png
    button:
      enable: false
      name: "Resume"
      url: "https://resume.creddle.io/resume/339b07suvix"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://example.com
        - icon: fab fa-twitter
          url: https://example.com
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. 

      I am currently working on a project that will be used to help people find the best way to get around the city.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Express"

  # Experience
  experience:
    enable: true
    items:
      - job: "Senior Software Engineer"
        company: "FactSet"
        companyUrl: "https://www.factset.com/"
        location: Boston, MA
        date: "Feb 2014 - present"
        content: |
          - Lead Developer in the News team, part of the Research Group which is responsible for building high value web applications within FactSet.
          - Architected and Implemented FactSet’s Next Gen News offering using the VueJS framework and TypeScript.
          - Led a team of 3 engineers in developing FactSet’s Streaming News API offering which is used by internal and external clients worldwide.
          - Built a suite of scalable web applications including Today’s Top News which is the home page for FactSet clients and receives millions of requests daily.  
          - Designed and developed web applications using the .NET framework and worked full stack with ASP, C# and SQL Server DB.
          - Developed high traffic applications using AngularJS, RESTful APIs and Express backend which was the base for FactSet’s Next Gen offerings.  

      - job: "Software Development Engineer Intern"
        company: "Microsoft"
        companyUrl: "https://www.microsoft.com/"
        location: Boston, MA
        date: "June 2013 - Aug 2013"
        info:
          enable: true
          content: Was part of the Foundry Intern Program and worked on accelerated web app development
        content: |
          - Designed, coded and published a Windows 8.1 app called Rememory as part of a team of five people.
          - Structured the app’s architecture using the MVVM pattern and built it from scratch.
          -	Followed the agile development process and worked under short sprints with big deliverables. 
          - Coded several modules of the app including Maps and Gestures in C# and XAML.

      - job: "Software Engineering Coop"
        company: "Intuit"
        companyUrl: "https://www.intuit.com/"
        location: San Diego, CA
        date: "July 2012 - Dec 2012"
        info:
          enable: false
        content: |
          - Coded several enhancements in the Core C++ tax engine that drives TurboTax.
          -	Enhanced the existing Ruby test framework which scrutinized the internal tools. 
          - Worked with different types of XML used internally and coded XSL transformations for internal and external clients

      - job: "Assistant Systems Engineer, Team Lead"
        company: "Tata Consultancy Services"
        companyUrl: "https://www.tcs.com/"
        location: Chennai, India
        date: "Sep 2009 - Aug 2011"
        info:
          enable: false
        content: |
          -	Lead a Quality Assurance Testing Team in the Retail Domain for the client Home Depot.
          -	Framed scenarios for the requirements given and devised test cases for the scenarios framed.
          -	Performed System and Regression Testing and fixed bugs in Action Script and Flex Code.


  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Master of Science - Computer Science"
        school:
          name: "Northeastern University"
          url: "https://www.northeastern.edu/"
        date: "2011 - 2013"
        GPA: "3.9/4.0"
        content: |-
          Related Courses:
            - Artificial Intelligence,	Algorithms, Web Development, Parallel Data Processing using Map Reduce, Machine Learning 
      - title: "Bachelor of Engineering - Computer Science"
        school:
          name: "College of Engineering, Guindy"
          url: "https://ceg.annauniv.edu/"
        date: "2005 - 2009"
        GPA: "7.2/10"
        content: |-
          Related Courses:
          - Operating Systems, Database Management, Data Warehousing and Data Mining, Grid Computing, Object Oriented Analysis and Design, Distributed Systems.
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: false
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: false
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: gurusabarisha@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com
